# Generated by Django 3.1.7 on 2021-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('fp', models.SlugField(max_length=32)),
                ('components', models.JSONField(null=True)),
            ],
        ),
    ]
